### ISSUE TITLE
Methods/Functions are mentioned several times

### ISSUE THREAD

**Issue by yafp** [andstor/jsdoc-action#12]
While i now have your action running i am starting to check the resulting output. At least for me it looks like my module functions are mentioned several times in the resulting html output.

**Example output:**
[https://yafp.github.io/media-dupes/module-ffmpeg.html](https://yafp.github.io/media-dupes/module-ffmpeg.html)

**Related js source file:**
[https://github.com/yafp/media-dupes/blob/master/app/js/modules/ffmpeg.js](https://github.com/yafp/media-dupes/blob/master/app/js/modules/ffmpeg.js)

**Related jsdoc config file:**
[https://github.com/yafp/media-dupes/blob/master/jsdoc.json](https://github.com/yafp/media-dupes/blob/master/jsdoc.json)

**Related action:**
[https://github.com/yafp/media-dupes/actions?query=workflow%3A%22GitHub+pages%22](https://github.com/yafp/media-dupes/actions?query=workflow%3A%22GitHub+pages%22)

This does not happens if i generate them manually.

Any idea what might cause this?

**Comment by yafp** [comment]
Seems like it happens for all my .js files besides main.js (for this particular file it seems correct)

Could that be related with using `source_dir` in the first place?

**Background:** 
my current `source_dir` definition in the action does not include my main.js file, but still it is included in the resulting output. This might be related with my jsdoc config file as well.

**Question:**
According to your documentation `source_dir `is required - is that valid as well if there is a user-specific jsdoc.json config file (which defines the sources and exclude patterns)?
Having the ability to define source / include and exclude patterns in a jsdoc config looks way more flexible to me then just defining a single source dir.

**Comment by andstor** [comment]
Yes, it seems that this is due to specifying source files in the `source_dir` and also the same files in the config file. I agree that if one are using a **config file**, the `source_dir` should be optional. Will try to fix this today.

**Comment by andstor** [comment]
`source_dir`is now made optional in release [v1.1.0](https://github.com/andstor/jsdoc-action/releases/tag/v1.1.0).

**Comment by yafp** [comment]
@andstor 
thanks -  i'll report back after having tested it.

**Comment by yafp** [comment]
looks good. Thanks once again.
