### ISSUE TITLE
Need help with running jsdoc-action with my local repo

### ISSUE THREAD

**Issue by chinmay-kothari** [andstor/jsdoc-action#18]

**Comment by chinmay-kothari** [comment]
I am getting an error in the 
`- name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: conf.json
          front_page: README.md` 

It is unable to find the module 'escape-string-regexp' module. Maybe it's not getting installed properly. I really need help with this and I would be glad if you can help in any sort of way.

**Comment by andstor** [comment]
Hi!
I have checked out your current setup and the config and workflow file seems OK to me. I have tested your repo and I am able to generate documentation with your current files.

So, your action is able to build the documentation. However, it is not able to deploy it to GitHub Pages. It gives the error: `Error loading key "/home/runner/.ssh/github": invalid format`. The problem seems to be your `secret` (ssh key) for deploying. I suggest you recreate the secret and try to add it again. 

See the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key) action's guide for [how to create a SSH deploy key](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key).

**Comment by chinmay-kothari** [comment]
Hi!
Sorry for deleting the previous comments, I thought this not the correct place to ask my query.

Thanks for the reply! I really appreciate it.

I tried to generate another `secret key` and its working now. Can you tell me how can I see the generated GitHub page and also what to write in `template_name` in case I am using the default JSDoc.
Also, my out directory is still empty, aren't we supposed to get the generated files there.

Thanks

**Comment by andstor** [comment]
> Hi!
> Sorry for deleting the previous comments, I thought this not the correct place to ask my query.

No problem 👌

> Thanks for the reply! I really appreciate it.

Happy to help 😄 

> I tried to generate another `secret key` and its working now. Can you tell me how can I see the generated GitHub page and also what to write in `template_name` in case I am using the default JSDoc.

The documentation is available at: https://chinmay-kothari.github.io/DocsExample/

> Also, my out directory is still empty, aren't we supposed to get the generated files there.

The documentation in the `out` dir generated by the jsdoc-action only exists in the running VM. Once generated, other actions (such as actions-gh-pages) can be used to deploy the built files. This way, one are not limited to deploying to just GitHub Pages. It's just a matter of finding a suitable GitHub Action. Once the action finishes running, all the built files in the VM is deleted.

If you actually want to commit the built files (the `out` dir) into your GitHub repository, I am certain that there exists a GitHub Action for that in the [Marketplace](https://github.com/marketplace?type=actions).

**Comment by chinmay-kothari** [comment]
I really appreciate your help. Thanks a lot!

**Comment by chinmay-kothari** [comment]
Sorry for bothering you again. But when I made some changes to my repo like adding and deleting files. The link you mentioned isn't showing those changes. 

So does it make another link every time (if yes then how to get that link), or we can create the documentation webpage just once.

And also if I made any subdirectory in my `src` then will it be shown there?
Sorry for opening this issue again

**Comment by andstor** [comment]
No, it is still the same link. All changes in the source directory should be reflected on the GitHub Pages. Although, it does takes some time for the changes to become effective. If you don't see any changes after some time, you should clear your browser's cache.... However, simply a hard refresh should be sufficient. See [here](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache).

For including subdirectories under `src`, set the input variable `recurse` to `true` in your workflow file (yml), or specify it in your JSDoc config file.

I also see that I forgot to say what you should put in the `template_name` variable. If you want to use a template, specify the name of the template (the name used for publishing on [npm](https://www.npmjs.com)). If you just want to use the default JSDoc template, just don't add the `template_name` variable at all.

**Comment by chinmay-kothari** [comment]
Asking about the subdirectories, will they be shown or it just reads the file stored in src and not the files stored in a subdirectory. Or may should I mention the seperately in `source_dir` section.

Thanks for the template advice!

**Comment by andstor** [comment]
See my edited answer above ⬆️ 
But yes, if you set the recurse variable, all files in subdirectories will be included 👌

Also, if you like this action, please consider giving it a star ⭐️

**Comment by chinmay-kothari** [comment]
Sure man no problem. Thanks for helping me!!
