### ISSUE TITLE
How to use a github repo as template?

### ISSUE THREAD

**Issue by Androz2091** [andstor/jsdoc-action#20]
Hello,
I forked the minami repository. The package URL is now Androz2091/minami. It's successfully installed:

![Capture d’écran 2020-04-19 à 10 35 00](https://user-images.githubusercontent.com/42497995/79683312-74055d00-8229-11ea-807e-15e3d6f74274.png)

But, the package name is still "minami", not "Androz2091/minami". So the package is not found in the `node_modules` folder.

This problem concerns every template published on github, as the npm package name is `AUTHOR/TEMPLATE_NAME`. Maybe if the `template_name` includes a `/`, it would be possible to split on it and to keep the second string...

**Comment by andstor** [comment]
Hi, thanks for reporting this!
I agree that this is a problem that needs to be addressed indeed.

> Maybe if the template_name includes a /, it would be possible to split on it and to keep the second string...

Yes, this would work for a lot of actual use cases. However, lets say you want to install a specific version of a package. For example `minami@1.1.0`. This would also set the name of the package to `minami@1.1.0` and not `minami`. Several other cases shows similar problems.

We should try to support most of the installation options in the npm [documentation](https://docs.npmjs.com/cli/install).

So, technically speaking, the only way to make sure that the name of the package is resolved correctly, while still providing the user with maximum flexibility in terms of installation options, is to either:
1. have a separate `template_name` and `template_install` input variables.
2. preserve the current `template_name` variable and parse the installed template's `package.json`'s `name` entry.

I think I might fall towards option 2. It doesn't increase the number of input variables, keeping the action relatively simple to use.

**Comment by Androz2091** [comment]
Yes, I agree, the second option is better. I could've made a PR for the first one but not the second sorry 😅

**Comment by andstor** [comment]
OK, no problem👌
I will try to get option 2 implemented as soon as possible then.

Stay tuned 📻!

**Comment by andstor** [comment]
This issue is resolved in [v1.2.0](https://github.com/andstor/jsdoc-action/releases/tag/v1.2.0) 👌 It should now be possible to use your GitHub repo as a template. Note that there are some changes regarding input variables. See the [CHANGELOG.md](https://github.com/andstor/jsdoc-action/blob/master/CHANGELOG.md#120---2020-04-21)

Also, if you like this action, please consider giving it a star ⭐️

**Comment by Androz2091** [comment]
Thank you very much!
*Star added.*
